#ifndef __INC_AFFECT_H
#define __INC_AFFECT_H

class CAffect
{
	public:
		DWORD	dwType;
		BYTE    bApplyOn;
		long    lApplyValue;
		DWORD   dwFlag;
		long	lDuration;
		long	lSPCost;

		static CAffect* Acquire();
		static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_MOV_SPEED		= 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX,			// 205
	AFFECT_CON,	
	AFFECT_INT,	
	AFFECT_FISH_MIND_PILL,

	AFFECT_POISON,
	AFFECT_STUN,		// 210
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,

	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE,	// 215
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,

	AFFECT_POLYMORPH,		// 220
	AFFECT_MOUNT,

	AFFECT_WAR_FLAG,		// 222

	AFFECT_BLOCK_CHAT,		// 223
	AFFECT_CHINA_FIREWORK,

	AFFECT_BOW_DISTANCE,	// 225
	AFFECT_DEF_GRADE,		// 226
#ifdef ENABLE_NEW_PET_SYSTEM
	AFFECT_PET				= 227,
#endif

	AFFECT_PREMIUM_START	= 500,
	AFFECT_EXP_BONUS		= 500,	// 경험의 반지
	AFFECT_ITEM_BONUS		= 501,	// 도둑의 장갑
	AFFECT_SAFEBOX		= 502,  // PREMIUM_SAFEBOX,
	AFFECT_AUTOLOOT		= 503,	// PREMIUM_AUTOLOOT,
	AFFECT_FISH_MIND		= 504,	// PREMIUM_FISH_MIND,
	AFFECT_MARRIAGE_FAST	= 505,	// 원앙의 깃털
	AFFECT_GOLD_BONUS		= 506,	// 돈 드롭확률 50%증가
	AFFECT_AUTOHUNT		= 507,
	AFFECT_PREMIUM_END		= 509,

	AFFECT_MALL			= 510,	// 몰 아이템 에펙트
	AFFECT_NO_DEATH_PENALTY	= 511,	// 용신의 가호 (경험치가 패널티를 한번 막아준다)
	AFFECT_SKILL_BOOK_BONUS	= 512,	// 선인의 교훈 (책 수련 성공 확률이 50% 증가)
	AFFECT_SKILL_NO_BOOK_DELAY	= 513,	// 주안술서

	AFFECT_HAIR	= 514,	// 헤어 효과
	AFFECT_COLLECT = 515, //수집퀘스트 
	AFFECT_EXP_BONUS_EURO_FREE = 516, // 경험의 반지 (유럽 버전 14 레벨 이하 기본 효과)
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_CUBE_1,
	AFFECT_CUBE_2,
	AFFECT_CUBE_3,
	AFFECT_CUBE_4,
	AFFECT_CUBE_5,
	AFFECT_CUBE_6,
	AFFECT_CUBE_7,
	AFFECT_CUBE_8,
	AFFECT_CUBE_9,
	AFFECT_CUBE_10,
	AFFECT_CUBE_11,
	AFFECT_CUBE_12,

	AFFECT_BLEND,

	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,

	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING	   = 301,

	AFFECT_NOG_ABILITY = 302,
	AFFECT_SHADOW_POTION = 582,
#ifdef __NEW_BLEND_AFFECT__
	AFFECT_BLEND_POTION_1 = 304,
	AFFECT_BLEND_POTION_2 = 305,
	AFFECT_BLEND_POTION_3 = 306,
	AFFECT_BLEND_POTION_4 = 307,
	AFFECT_BLEND_POTION_5 = 308,
	AFFECT_BLEND_POTION_6 = 309,
	AFFECT_ENERGY = 310,
	AFFECT_BLEND_POTION_7 = 311,
	AFFECT_BLEND_POTION_8 = 312,
	AFFECT_BLEND_POTION_9 = 313,
	AFFECT_BLEND_POTION_10 = 314,
	AFFECT_BLEND_POTION_11 = 315,
	AFFECT_BLEND_POTION_12 = 316,
	AFFECT_BLEND_POTION_13 = 317,
#endif

	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,

	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,	
#ifdef ENABLE_TITLE_SYSTEM
	PRESTIGE_AFFECT_1 = 543,
	PRESTIGE_AFFECT_2 = 544,
	PRESTIGE_AFFECT_3 = 545,
#endif
#ifdef ENABLE_NEW_PET_SYSTEM
	AFFECT_NEW_PET = 559,
#endif
#ifdef __AUTO_PICKUP__		
	AFFECT_AUTO_PICKUP = 590, 
#endif
#ifdef __VIP_SYSTEM__
	AFFECT_VIP = 591,
#endif	
#ifdef __MELEY_LAIR_DUNGEON__
	AFFECT_STATUE = 700,
#endif
#ifdef __RENEWAL_BRAVE_CAPE__
	AFFECT_BRAVE_CAPE = 813,
#endif
#ifdef ENABLE_OFFLINESHOP_SYSTEM
	AFFECT_DECORATION = 703,
#endif
	AFFECT_QUEST_START_IDX = 1000
	
};

enum EAffectBits
{   
	AFF_NONE,

	AFF_YMIR,
	AFF_INVISIBILITY,
	AFF_SPAWN,

	AFF_POISON,
	AFF_SLOW,
	AFF_STUN,

	AFF_DUNGEON_READY,		// 던전에서 준비 상태
	AFF_DUNGEON_UNIQUE,		// 던전 유니크 (클라이언트에서 컬링되지않음)

	AFF_BUILDING_CONSTRUCTION_SMALL,
	AFF_BUILDING_CONSTRUCTION_LARGE,
	AFF_BUILDING_UPGRADE,

	AFF_MOV_SPEED_POTION,	// 11
	AFF_ATT_SPEED_POTION,	// 12

	AFF_FISH_MIND,		// 13

	AFF_JEONGWIHON,		// 14
	AFF_GEOMGYEONG,		// 15
	AFF_CHEONGEUN,		// 16
	AFF_GYEONGGONG,		// 17
	AFF_EUNHYUNG,		// 18
	AFF_GWIGUM,			// 19
	AFF_TERROR,			// 20
	AFF_JUMAGAP,		// 21
	AFF_HOSIN,			// 22
	AFF_BOHO,			// 23
	AFF_KWAESOK,		// 24
	AFF_MANASHIELD,		// 25
	AFF_MUYEONG,		// 26
	AFF_REVIVE_INVISIBLE,	// 27
	AFF_FIRE,			// 28
	AFF_GICHEON,		// 29
	AFF_JEUNGRYEOK,		// 30
	AFF_TANHWAN_DASH,		// 31
	AFF_PABEOP,			// 32
	AFF_CHEONGEUN_WITH_FALL,	// 33
	AFF_POLYMORPH,			// 34
	AFF_WAR_FLAG1,			// 35
	AFF_WAR_FLAG2,			// 36
	AFF_WAR_FLAG3,			// 37

	AFF_CHINA_FIREWORK,		// 38
	AFF_HAIR,	// 39
	AFF_GERMANY, // 40
#ifdef ITEM_BUFF_SYSTEM
	AFF_RESIST_BUFF,		
	AFF_CRITICAL_BUFF,		
	AFF_REFLECT_BUFF,		
#endif
#ifdef __VIP_SYSTEM__
	AFF_VIP, 
#endif	
#ifdef __MELEY_LAIR_DUNGEON__
	AFF_STATUE1,
	AFF_STATUE2,
	AFF_STATUE3,
	AFF_STATUE4,
#endif
#ifdef ENABLE_PREMIUM_SYSTEM
	AFF_PREMIUM	= 60,
#endif
#ifdef ENABLE_REBORN_SYSTEM
	AFFECT_REBORN_1_A,
	AFFECT_REBORN_1_B,
	AFFECT_REBORN_1_C,
	AFFECT_REBORN_1_D,

	AFFECT_REBORN_2_A,
	AFFECT_REBORN_2_B,
	AFFECT_REBORN_2_C,
	AFFECT_REBORN_2_D,

	AFFECT_REBORN_3_A,
	AFFECT_REBORN_3_B,
	AFFECT_REBORN_3_C,
	AFFECT_REBORN_3_D,
#endif
	AFF_BITS_MAX,
};

extern void SendAffectAddPacket(LPDESC d, CAffect * pkAff);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	// Affect가 무한대로 들어가 있어야 할 경우 사용.
	// 시간을 계속 줄이기 때문에 매우 큰값으로 무한대를 에뮬레이션함.
	//// 24비트는 적으므로 25비트를 사용.
	// ... 25비트 사용한다고 해놓고선 29bit 사용하고 있는 엄청난 주석이란...
	// collect quest에서 무한 시간을 60년으로 사용하고 있으므로, 여기도 60년으로 하자.

	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};
// END_AFFECT_DURATION_BUG_FIX

#endif
